apiVersion: v1
kind: Pod
metadata:
  name: time-frontend
  labels:
    app-type: frontend
spec:
  containers:
  - name: frontend
    image: jrac/time-frontend:v1
    ports:
    - containerPort: 5000
    envFrom:
      - configMapRef:
          name: frontend-configmap
