kind: Service
apiVersion: v1
metadata:
  name: time-frontend-service
spec:
  type: NodePort
  selector:
    app-type: frontend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30008
