---
- hosts: all
  become: true
  tasks:
  
  - name: Install prerequisites
    import_role:
      name: common

  - name: Install Docker
    import_role:
      name: docker-runtime

  - name: Install Kubernetes
    import_role:
      name: k8s-control-plane

  handlers:
  - name: docker status
    service: name=docker state=started