---
- hosts: all
  become: true
  roles:
    - common
    - containerd
    - kubernetes
    - kubernetes-control-plane
  handlers:
  - name: containerd status
    service: name=containerd state=started
