IMAGE_NAME = "bento/ubuntu-16.04"
NUM_WORKERS = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box = IMAGE_NAME

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2

        # disable USB support
        v.customize ["modifyvm", :id, "--usb", "off"]
        v.customize ["modifyvm", :id, "--usbehci", "off"]
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.60.10"
        master.vm.hostname = "k8s-master"

        master.vm.provision "file", source: "ansible/master-playbook.yml", destination: "/home/vagrant/master-playbook.yml"
        master.vm.provision "file", source: "ansible/files/daemon.json", destination: "/home/vagrant/ansible/files/daemon.json"

        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "/home/vagrant/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.60.10",
            }
        end
    end

    (1..NUM_WORKERS).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.60.#{i + 10}"
            node.vm.hostname = "k8s-node-#{i}"

            node.vm.provision "file", source: "ansible/node-playbook.yml", destination: "/home/vagrant/node-playbook.yml"
            node.vm.provision "file", source: "ansible/files/daemon.json", destination: "/home/vagrant/ansible/files/daemon.json"

            node.vm.provision "ansible_local" do |ansible|
                ansible.playbook = "/home/vagrant/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.60.#{i + 10}",
                }
            end
        end
    end
end
