NUM_WORKERS = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box = "ubuntu/focal64"

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2

        # disable USB support
        v.customize ["modifyvm", :id, "--usb", "off"]
        v.customize ["modifyvm", :id, "--usbehci", "off"]
    end

    config.vm.define "control-plane" do |cplane|
        cplane.vm.network "private_network", ip: "192.168.60.10"
        cplane.vm.network "forwarded_port", guest: 6443, host: 6443
        cplane.vm.hostname = "control-plane"

        cplane.vm.provision "file", source: "ansible", destination: "/home/vagrant/ansible"

        cplane.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "/home/vagrant/ansible/cplane.yml"
            ansible.extra_vars = {
                name: "control-plane", ip: "192.168.60.10", cidr: "192.168.0.0/16"
            }
        end

        cplane.vm.network "forwarded_port", guest: 443, host: 8080
        cplane.vm.network "forwarded_port", guest: 6443, host: 8090
    end

    (1..NUM_WORKERS).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.network "private_network", ip: "192.168.60.#{i + 10}"
            node.vm.hostname = "node-#{i}"

            node.vm.provision "file", source: "ansible", destination: "/home/vagrant/ansible"
            
            node.vm.provision "ansible_local" do |ansible|
                ansible.playbook = "/home/vagrant/ansible/node.yml"
                ansible.extra_vars = {ip: "192.168.60.#{i + 10}"}
            end
        end
    end
end
