apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend

  labels:
    app-type: frontend

spec:
  template:
    metadata:
      labels:
        app-type: frontend

    spec:
      containers:
      - name: frontend
        image: jrac/time-frontend:v1
        ports:
          - containerPort: 5000

        env:
          - name: TIME_SERVER
            valueFrom:
              configMapKeyRef:
                name: frontend-configmap
                key: backend

  replicas: 3
  selector:
    matchLabels:
      app-type: frontend
