apiVersion: v1
kind: Service

metadata:
  name: frontend-service

spec:
  type: NodePort

  selector:
    app-type: frontend

  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30001
