apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-backend
  labels:
    app-type: backend
spec:
  template:
    metadata:
      labels:
        app-type: backend
    spec:
      containers:
      - name: backend-implementation
        image: jrac/time-backend:v1
        ports:
        - containerPort: 5000

  replicas: 3
  selector:
    matchLabels:
      app-type: backend
