apiVersion: v1
kind: Pod
metadata:
  name: time-backend
  labels:
    app-type: backend
spec:
  containers:
  - name: backend-implementation
    image: jrac/time-backend:v1
    ports:
    - containerPort: 5000
