apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-frontend
  labels:
    app-type: frontend
spec:
  template:
    metadata:
      labels:
        app-type: frontend
    spec:
      containers:
      - name: frontend-implementation
        image: jrac/time-frontend:v1
        ports:
        - containerPort: 5000
