apiVersion: v1
kind: Pod
metadata:
  name: time-frontend
spec:
  containers:
  - name: frontend
    image: jrac/time-frontend:v1
    ports:
    - containerPort: 5000
    env:
        - name: TIME_SERVER
          value: "time-backend-service:5000"
